### PR TITLE
Added additional converters for Owner

### PR DESCRIPTION
**Pull request by tobias-bahls**
Namely PathConverter and DurationConverter which will probably be useful.

### CODE REVIEW

**Comment by fatroom** [comment]
👍

**Comment by fatroom** [comment]
I missed something, but is there Stamped converter already exists?

**Comment by cberg-zalando** [comment]
I would guess no.

**Comment by cberg-zalando** [comment]
:+1:

**Comment by tobias-bahls** [comment]
@cberg-zalando is right. There were no 'official' converters for these types. There is something in owner-java8-extras, but that project isn't published in any maven repository

**Comment by fatroom** [comment]
Nevermind regarding Stamped, i was thinking that it belongs to Undertaking, but turned out that it's own own thing inside one of the projects.

**Pull request merged**
