### PR TITLE
Trigger Maven wrapper download before executing anything serious

### PR DESCRIPTION
**Pull request by cberg-zalando**

### CODE REVIEW

**Comment by fatroom** [comment]
Isn't maven wrapper downloaded automagically on first run?

**Comment by cberg-zalando** [comment]
It is, but if you don't have the wrapper installed, you get the output of the Java program written to stdout, which results in a version proposal like

```
Use Downloading https://repo1.maven.org/maven2/org/apache/maven/apache
..............................................................................................................................................................................................................................................................................................................................................................................................................................................                                                        
Unzipping /home/cberg/.m2/wrapper/dists/apache                                                                                                                                                                                                     
Set executable permissions for: /home/cberg/.m2/wrapper/dists/apache                                                                                                                                                                               
0.0.2 as new release version? (Y/n) n
```

**Comment by fatroom** [comment]
👍

**Comment by jans510** [comment]
:+1:

**Comment by cberg-zalando** [comment]
:+1:

**Pull request merged**
